name: doid-suite
region: fra

# Global environment variables (set in DigitalOcean dashboard)
# SUPABASE_URL, SUPABASE_ANON_KEY, SUPABASE_SERVICE_KEY, JWT_SECRET, SUPER_ADMIN_EMAILS

# Backend API Service
services:
  - name: api
    github:
      repo: doiddoid/doid-suite
      branch: main
      deploy_on_push: true
    source_dir: backend
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    http_port: 3001
    routes:
      - path: /api
        preserve_path_prefix: true
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3001"
      - key: JWT_EXPIRES_IN
        value: "7d"
      - key: JWT_EXTERNAL_EXPIRES_IN
        value: "5m"
      - key: FRONTEND_URL
        value: ${APP_URL}
    build_command: npm install
    run_command: npm start
    health_check:
      http_path: /health

# Frontend Static Site
static_sites:
  - name: frontend
    github:
      repo: doiddoid/doid-suite
      branch: main
      deploy_on_push: true
    source_dir: frontend
    build_command: npm install && npm run build
    output_dir: dist
    index_document: index.html
    error_document: index.html
    routes:
      - path: /
    envs:
      - key: VITE_API_URL
        value: ${APP_URL}/api
