name: doid-suite
region: fra

# Backend API Service
services:
  - name: api
    github:
      repo: doiddoid/doid-suite
      branch: main
      deploy_on_push: true
    source_dir: backend
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    http_port: 3001
    routes:
      - path: /api
        preserve_path_prefix: true
    envs:
      - key: NODE_ENV
        scope: RUN_AND_BUILD_TIME
        value: production
      - key: PORT
        scope: RUN_AND_BUILD_TIME
        value: "3001"
      - key: JWT_EXPIRES_IN
        scope: RUN_AND_BUILD_TIME
        value: "7d"
      - key: JWT_EXTERNAL_EXPIRES_IN
        scope: RUN_AND_BUILD_TIME
        value: "5m"
      - key: FRONTEND_URL
        scope: RUN_AND_BUILD_TIME
        value: ${APP_URL}
      - key: SUPABASE_URL
        scope: RUN_AND_BUILD_TIME
        value: https://uephzdezzfevxifagcjo.supabase.co
      - key: SUPABASE_ANON_KEY
        scope: RUN_AND_BUILD_TIME
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVlcGh6ZGV6emZldnhpZmFnY2pvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ2OTIzNDgsImV4cCI6MjA4MDI2ODM0OH0.qG7nS4TB4onNudOZuGAdt772znDKzr9A5Z-JpravTDQ
      - key: SUPABASE_SERVICE_KEY
        scope: RUN_AND_BUILD_TIME
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVlcGh6ZGV6emZldnhpZmFnY2pvIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2NDY5MjM0OCwiZXhwIjoyMDgwMjY4MzQ4fQ.J1AsqkmIK-ZrRsBvhlMDl3HIHmnjeD9RJaVbUIq-cuU
      - key: JWT_SECRET
        scope: RUN_AND_BUILD_TIME
        value: xR5n3To0YR6REwVzzlU9aObWozfZY3OzaLva/9aeTvY=
      - key: SUPER_ADMIN_EMAILS
        scope: RUN_AND_BUILD_TIME
        value: admin@doid.it
    build_command: npm install
    run_command: npm start
    health_check:
      http_path: /health

# Frontend Static Site
static_sites:
  - name: frontend
    github:
      repo: doiddoid/doid-suite
      branch: main
      deploy_on_push: true
    source_dir: frontend
    build_command: npm install && npm run build
    output_dir: dist
    index_document: index.html
    error_document: index.html
    routes:
      - path: /
    envs:
      - key: VITE_API_URL
        scope: RUN_AND_BUILD_TIME
        value: https://doid-suite-e9i5o.ondigitalocean.app/api
      - key: VITE_SUPABASE_URL
        scope: RUN_AND_BUILD_TIME
        value: https://uephzdezzfevxifagcjo.supabase.co
      - key: VITE_SUPABASE_ANON_KEY
        scope: RUN_AND_BUILD_TIME
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVlcGh6ZGV6emZldnhpZmFnY2pvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ2OTIzNDgsImV4cCI6MjA4MDI2ODM0OH0.qG7nS4TB4onNudOZuGAdt772znDKzr9A5Z-JpravTDQ
